version: 2
enable-beta-ecosystems: true
updates:
  - package-ecosystem: "github-actions"
    directory: "/.github/workflows"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 50
#  - package-ecosystem: "npm"
#    directory: "/"
#    schedule:
#      interval: "daily"
#    open-pull-requests-limit: 50
  # - package-ecosystem: "pip"
  #   directory: "/"
  #   schedule:
  #     interval: "daily"
  #     open-pull-requests-limit: 50